[buildPlans.IosevkaOrzoNL]
family = "Iosevka Orzo NL"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
buildTextureFeature = true
noLigation = true

  [buildPlans.IosevkaOrzoNL.variants]
  inherits = "ss14" # "JetBrains Mono"

    [buildPlans.IosevkaOrzoNL.variants.design]
    apl-form = "enable"

    zero = "slashed"
    capital-k = "straight-serifless"
    capital-q = "curly-tailed"
    capital-w = "straight-serifless"
    f = "flat-hook-serifless"
    g = "single-storey-serifless"
    i = "serifed-asymmetric"
    j = "serifed"
    k = "straight-serifless"
    t = "bent-hook-short-neck"
    u = "toothed-serifless"
    w = "straight-serifless"
    long-s = "flat-hook-tailed"
    lower-alpha = "crossing"
    lower-gamma = "casual"
    lower-theta = "oval"
    lower-lambda = "tailed-turn"
    lower-nu = "casual"
    lower-upsilon = "casual-serifed"
    cyrl-capital-ka = "straight-serifless"
    cyrl-ka = "straight-serifless"
    paren = "normal"
    brace = "straight"
    question = "smooth"
    lig-ltgteq = "flat"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"

[buildPlans.IosevkaOrzoNL.widths.Normal]
shape = 564
menu = 5
css = "normal"


[buildPlans.IosevkaOrzoNL.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaOrzoNL.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"


[buildPlans.IosevkaOrzo]
family = "Iosevka Orzo"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
buildTextureFeature = true
noLigation = false

variants.inherits = "buildPlans.IosevkaOrzoNL"
weights.inherits  = "buildPlans.IosevkaOrzoNL"
widths.inherits   = "buildPlans.IosevkaOrzoNL"
slopes.inherits   = "buildPlans.IosevkaOrzoNL"

[buildPlans.IosevkaOrzo.ligations]
  inherits = "default-calt"
  disables = [
    "center-ops", # Vertically align some of the operators (like *) to the center position it is before or after a "center" operator (like +).
    "center-op-trigger-plus-minus-l", # Plus (+) and Minus (-) will trigger other operator characters at left to be centered.
    "center-op-trigger-plus-minus-r", # Plus (+) and Minus (-) will trigger other operator characters at right to be centered.
    "center-op-trigger-equal-l", # Equal (=) will trigger other operator characters at left to be centered.
    "center-op-trigger-equal-r", # Equal (=) will trigger other operator characters at right to be centered.
    "center-op-trigger-bar-l", # Bars (|) will trigger other operator characters at left to be centered.
    "center-op-trigger-bar-r", # Bars (|) will trigger other operator characters at right to be centered.
    "center-op-trigger-angle-inside", # Less (<) and Greater (>) will trigger other operator characters at inside to be centered.
    "center-op-trigger-angle-outside", # Less (<) and Greater (>) will trigger other operator characters at outside to be centered.
    "center-op-influence-dot", # Treat dot (.) as operator and perform chained centering.
    "center-op-influence-colon", # Treat colon (:) as operator and perform chained centering.

    "trig",           # <|, |> , <||, and other bar-and-angle-bracket symbols
    "ltgt-slash-tag", # </, /> and </>
    "exeqeqeq"        # !=== with triple lines
  ]