[buildPlans.IosevkaOrzo]
family = "Iosevka Orzo"
spacing = "fixed"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.IosevkaOrzo.variants]
  inherits = "ss14"

    [buildPlans.IosevkaOrzo.variants.design]
    zero = "slashed"
    capital-q = "curly-tailed"
    capital-w = "straight-serifless"
    f = "flat-hook-serifless"
    g = "single-storey-serifless"
    i = "serifed-asymmetric"
    j = "serifed"
    k = "straight-serifless"
    t = "bent-hook-short-neck"
    u = "toothed-serifless"
    w = "straight-serifless"
    paren = "normal"
    brace = "straight"
    question = "smooth"
    lig-ltgteq = "flat"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "with-notch"
    lig-plus-chain = "with-notch"

[buildPlans.IosevkaOrzo.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaOrzo.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaOrzo.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaOrzo.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaOrzo.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaOrzo.widths.SemiCondensed]
shape = 548
menu = 4
css = "semi-condensed"
